### ISSUE TITLE
User Confirmation

### ISSUE THREAD

**Issue by ameliebawolski** [bcc-code/bcc-vote#116]
**User Story**
As an admin , I want to participants to confirm that they are the logged in user so that administrator can be sure it's them

**Acceptance Criteria**
1. this should get up when ever a  user is joining an event:
2.   You are confirmating that you are voing as [name of logged in user]. If you are not this user please log out. 
2. confirm with okay button

**Comment by lidalukashuk** [comment]
@ameliebawolski design for user confirmation is ready: 

Mobile: https://www.figma.com/file/Eq4kNcMejzrIQWV6sD4e0C/BCC-Voting?node-id=583%3A133

Desktop: https://www.figma.com/file/Eq4kNcMejzrIQWV6sD4e0C/BCC-Voting?node-id=583%3A203
