### ISSUE TITLE
Sign out button 

### ISSUE THREAD

**Issue by ameliebawolski** [bcc-code/bcc-vote#131]
**Acceptance Criteria**
1. sign out button - User should be able to log out and log in again

**Comment by lidalukashuk** [comment]
@philipdalen @ameliebawolski 

https://www.figma.com/file/Eq4kNcMejzrIQWV6sD4e0C/BCC-Voting?node-id=121%3A3221

![Uploading Screenshot 2021-06-08 at 11.10.41.png…]()
