### ISSUE TITLE
time on start page vs detail view of polling event

### ISSUE THREAD

**Issue by ameliebawolski** [bcc-code/bcc-vote#133]
**User Story**
As a .... , I want to .... so that ....

![image](https://user-images.githubusercontent.com/69782899/121022527-b29a0600-c7a2-11eb-8b6c-380bfb0b6343.png)

![image](https://user-images.githubusercontent.com/69782899/121022447-9eee9f80-c7a2-11eb-993a-e9780d1336a4.png)

**Acceptance Criteria**
1. time on the start page should be the same as set in the polling event

**Comment by StevenMalaihollo** [comment]
@ameliebawolski could you define this a bit more? The scheduledDate is being used so it is the same date. 

But is the display maybe not clear enough?

**Comment by JakubC-projects** [comment]
What I think happens is that the date is displayed in 12 hour format instead of 24 hour format
