### ISSUE TITLE
Admin- present voting results live 

### ISSUE THREAD

**Issue by ameliebawolski** [bcc-code/bcc-vote#141]
**User Story**
As an administrator , I want to present results live so that all participants are informed

**Acceptance Criteria**
1.  Button on live event: show results live
2. button should be disabled when event not started
3. Button should be active when event started
2. Should open an own tab
3. should always show the currently presented question and the results
4. Results should be kept there even if question is closed
5. Next question should autmatically come up as soon it's published 
6. Avstemninger = poll results
7. deltaker = participants
8. 34 deltaker har stemt - we don't do this now

**Comment by lidalukashuk** [comment]
https://www.figma.com/file/Eq4kNcMejzrIQWV6sD4e0C/BCC-Voting?node-id=643%3A1391

@ameliebawolski

**Comment by lidalukashuk** [comment]
Before the meeting starts:
https://www.figma.com/file/Eq4kNcMejzrIQWV6sD4e0C/BCC-Voting?node-id=467%3A41

When event is active:
https://www.figma.com/file/Eq4kNcMejzrIQWV6sD4e0C/BCC-Voting?node-id=212%3A524
