### ISSUE TITLE
Event creator should be able to join in the event they created

### ISSUE THREAD

**Issue by ameliebawolski** [bcc-code/bcc-vote#160]
**User Story**
As a .... , I want to .... so that ....

**Additional Description**
....

**Acceptance Criteria**
1. Event creator should be able to join in the event they created just as easly as "normal" participants
2. https://www.figma.com/file/Eq4kNcMejzrIQWV6sD4e0C/BCC-Voting?node-id=79%3A1032 follow design
3. administrate this event = administrate
4. join voting event = participate 
5. if an administrator is not within the voting groupe they should not be allowed to participate --> should only have administrate button
6. should be only possible to click on button

**Comment by lidalukashuk** [comment]
@ameliebawolski 

https://www.figma.com/file/Eq4kNcMejzrIQWV6sD4e0C/BCC-Voting?node-id=79%3A1032

**Comment by StevenMalaihollo** [comment]
This is possible since https://github.com/bcc-code/bcc-vote/issues/463
