### ISSUE TITLE
Republished question changes order of questions

### ISSUE THREAD

**Issue by ameliebawolski** [bcc-code/bcc-vote#161]
**User Story**
Republishing a question leads to a change in order of the question

https://web.microsoftstream.com/video/0b0e17ac-7fc0-4ac3-9505-4d6c92f65160

**Acceptance Criteria**
1. Order of questions should be kept even when a quesiton is republished, closed or anything else.

**Comment by StevenMalaihollo** [comment]
This was fixed some time ago.
