### ISSUE TITLE
Rename some buttons etc.

### ISSUE THREAD

**Issue by ameliebawolski** [bcc-code/bcc-vote#170]
**User Story**
As a .... , I want to .... so that ....

**Additional Description**
![image](https://user-images.githubusercontent.com/69782899/121382871-4e647700-c947-11eb-9e99-9d1e51089f75.png)

![image](https://user-images.githubusercontent.com/69782899/121412095-9c3ba800-c964-11eb-94fd-67630665ec58.png)
 

**Acceptance Criteria**
1. Create a polling event = + create polling event
2. Thank you for participating in this poll... --> empty

**Comment by StevenMalaihollo** [comment]
I believe this was done during the redesign.
