### ISSUE TITLE
thank you for participating

### ISSUE THREAD

**Issue by ameliebawolski** [bcc-code/bcc-vote#178]
**User Story**
As a .... , I want to .... so that ....

![image](https://user-images.githubusercontent.com/69782899/121526536-c25f5780-c9f9-11eb-8b7c-6a7bdea74eb9.png)

**Acceptance Criteria**
1. only thank you for participating! 
2. delet ethank you for participating...

**Comment by StevenMalaihollo** [comment]
The Thank you page has changed since the redesign
