### ISSUE TITLE
Voting for participants - Design feedback 

### ISSUE THREAD

**Issue by lidalukashuk** [bcc-code/bcc-vote#182]
1. Buttons on the first pop-up can be moved a little bit closer to the text. Not the best experience on the smaller screens. 
Same with the space between the buttons check here with the Norwegian labels: https://www.figma.com/file/Eq4kNcMejzrIQWV6sD4e0C/BCC-Voting?node-id=583%3A133

<img width="434" alt="Screenshot 2021-06-11 at 08 34 09" src="https://user-images.githubusercontent.com/33638539/121641686-cc339a00-ca8f-11eb-914c-471e6272f255.png">

2. The title of the vote event in live session and paddings around were changed: https://www.figma.com/file/Eq4kNcMejzrIQWV6sD4e0C/BCC-Voting?node-id=171%3A499

<img width="272" alt="Screenshot 2021-06-11 at 08 33 34" src="https://user-images.githubusercontent.com/33638539/121641635-b7570680-ca8f-11eb-81e1-8ce8604fbf5a.png">

3. "Bekreftelse" same spacing as on the first pop-up and the description text color should be #838CA8 (Label 3)
https://www.figma.com/file/Eq4kNcMejzrIQWV6sD4e0C/BCC-Voting?node-id=464%3A234

5. The text and paddings on the thank you screen was updated: https://www.figma.com/file/Eq4kNcMejzrIQWV6sD4e0C/BCC-Voting?node-id=361%3A101

**Comment by ameliebawolski** [comment]
@lidalukashuk they worked on the result page. So I don't know how relevant this is after they release that update..

**Comment by ameliebawolski** [comment]
is this still relevant nr. 4 @lidalukashuk ?

**Comment by lidalukashuk** [comment]
We've made changes on participants yesterday @ameliebawolski so I'm not sure tht they've been implemented

**Comment by ameliebawolski** [comment]
can you check @lidalukashuk

**Comment by lidalukashuk** [comment]
can we start the live poll? @ameliebawolski or is there any other way to test it? I can take a screenshot on the meeting now

**Comment by lidalukashuk** [comment]
@ameliebawolski I've updated The task :) The participants part looks nice
