### ISSUE TITLE
voting admin - not able to create new poll events

### ISSUE THREAD

**Issue by ameliebawolski** [bcc-code/bcc-vote#183]
**User Story**
Voting admin who are responsible for another church than they belong to, they can't create new poll events.
E.g. Eva belongs to Oslo but is a voting admin for Svartskog. She couldn't create voting events

**Acceptance Criteria**
1. voting admins should be able to create new poll events for the org they are responsible for even if they themself don't belong to this org
2. if they don't belong to this org they should just not be able to participate in that orgs votings

**Comment by StevenMalaihollo** [comment]
I believe this is resolved by the collaboration release recently
