### ISSUE TITLE
Vulnerability: Members can see everyone's votes

### ISSUE THREAD

**Issue by adelinn** [bcc-code/bcc-vote#186]
**User Story** 
As a user I want to be sure that my answers aren't visible to unauthorized people so that I can trust the system and use it securely.

**Additional Description**
Members can see all answers stored in the database and implicitly also the ones that should be anonymous.
To reproduce this you have to hook the websocket that talks with the backend and send a specially crafted request.
You can find the code for hooking here https://github.com/adelinn/socketio-hook
The crafted request is: 
`ws.send('423["find","answer",{}]')`

**Acceptance Criteria**
1. Members see only theirs answers and the ones that are public.

Root cause: 4256071751926a5821ec28cef9be1afabbfe441b

**Comment by StevenMalaihollo** [comment]
This has been resolved already. See this PR: https://github.com/bcc-code/bcc-vote/pull/230
