### ISSUE TITLE
Polling event details

### ISSUE THREAD

**Issue by ameliebawolski** [bcc-code/bcc-vote#197]
**User Story**
As a .... , I want to .... so that ....

**Additional Description**
....

**Acceptance Criteria**
1. show details on polling event after it was created
2. Follow the design  https://www.figma.com/file/Eq4kNcMejzrIQWV6sD4e0C/BCC-Voting?node-id=98%3A1668

**Comment by lidalukashuk** [comment]
Design: https://www.figma.com/file/Eq4kNcMejzrIQWV6sD4e0C/BCC-Voting?node-id=98%3A1668
