### ISSUE TITLE
Design change - buttons on home screen 

### ISSUE THREAD

**Issue by ameliebawolski** [bcc-code/bcc-vote#198]
**User Story**
As a .... , I want to .... so that ....

**Additional Description**
....

**Acceptance Criteria**
1. Update the buttons
2. Tags/Status - Color, size and styling was slightly changed after we changed the main color and added it to the event section
https://www.figma.com/file/Eq4kNcMejzrIQWV6sD4e0C/BCC-Voting?node-id=899%3A751
3. Updated design for the cards: https://www.figma.com/file/Eq4kNcMejzrIQWV6sD4e0C/BCC-Voting?node-id=921%3A138

**Comment by lidalukashuk** [comment]
1. Tags/Status - Color, size and styling was slightly changed after we changed the main color and added it to the event section
https://www.figma.com/file/Eq4kNcMejzrIQWV6sD4e0C/BCC-Voting?node-id=899%3A751

2. Updated design for the cards: https://www.figma.com/file/Eq4kNcMejzrIQWV6sD4e0C/BCC-Voting?node-id=921%3A138
