### ISSUE TITLE
Authentication - Existing user change find to get request

### ISSUE THREAD

**Issue by StevenMalaihollo** [bcc-code/bcc-vote#201]
**User Story**
As a .... , I want to .... so that ....

https://github.com/bcc-code/bcc-vote/blob/4bb2322c12edba454f262fae0d357c4e6e5be642/server/src/services/authentication/authentication.ts#L41

**Additional Description**
....

**Acceptance Criteria**
1.

**Comment by philipdalen** [comment]
I did a check and my evaluation on the current solution is that it is the best implementation, get requests assums that the object will be found, in this case we are not sure if the object will be found, for example in the case that it is the first time the user logs in.
