### ISSUE TITLE
Members can answer any pool

### ISSUE THREAD

**Issue by adelinn** [bcc-code/bcc-vote#217]
**User Story**
As an admin I want to be sure that the results of my polling events are accurate so that I can trust the system and make use of it.

**Additional Description**
Any user of the voting app has access through the API (websocket calls) to answer any poll.
To reproduce this you have to hook the websocket that talks with the backend and send a specially crafted request.

**Acceptance Criteria**
1. Users can vote only on polls in polling events they have access to.

Root cause: 4bb2322c12edba454f262fae0d357c4e6e5be642

**Comment by elpenny** [comment]
This was fixed in #335
