### ISSUE TITLE
The firebase database is the same for testing and production.

### ISSUE THREAD

**Issue by adelinn** [bcc-code/bcc-vote#238]
**User Story**
As an administrator, I want to get real results from the polling event I'm holding so that I can trust the system and continue using it.

**Additional Description**
It may happen that someone from our team could archive a polling event (that has the same id as the one that is in production) locally and this event gets synced with production through firebase and so everyone on production gets kicked out of that polling event.

**Acceptance Criteria**
1. Local testing won't affect production.
2. Local testing won't affect other members of the team testing environment.

Root cause: b6b6ff0109c1e55d3a9d72fe5665ef2bd79792fd

**Comment by StevenMalaihollo** [comment]
This was resolved by Jakubs change a month ago
