### ISSUE TITLE
Timeout error 

### ISSUE THREAD

**Issue by ameliebawolski** [bcc-code/bcc-vote#248]
**User Story**
https://projects.bcc.no/desk/tickets/6897549/messages

They had a timeout error 
Den som styrte spørsmålene måtte logge inn på nytt. Det måtte flere av deltakerne og.
Beskjeden var noe med timeout 5000 ms.

also Drammen got the same timeout issue:
https://projects.bcc.no/desk/tickets/6898616/messages

**Comment by StevenMalaihollo** [comment]
These incidents are taken in the tasks: #252 and #254
