### ISSUE TITLE
Users asked if they want to open link in BrunstadTV app

### ISSUE THREAD

**Issue by rvanoord** [bcc-code/bcc-vote#253]
Android users are asked if they want to open BCC Vote in Chrome or BrunstadTV app when they click on a link.

This happens when users are not logged in and are redirected to bcc-sso.

The underlying reason is that the BrunstadTV app also subscribes to the bcc-sso domain. A quick workaround is to use login.bcc.no as the auth domain instead of the bcc-sso domain. The long-term solution is to remove associations to auth from the BrunstadTV app (or assign a dedicated auth domain to the BTV app).

The problem is not isolated to BCC Vote, but is highly critical since it can effectively make it impossible to users to access BCC Vote (if they choose "always open" in BrunstadTV).

**Comment by KillerX** [comment]
@rvanoord I see the association in Android but not on iOs. Can you confirm that this is only an issue on Android?

**Comment by philipdalen** [comment]
@KillerX me and Reng tested it, it is indeed only Android

**Comment by KillerX** [comment]
Ok, I have submitted a PR to remove that association, as in my testing this is not used at all. Should be released in the 3.7 series, but likely not before end of next week (3.7 has some major features that are being wrapped up).
