### ISSUE TITLE
Votes displayed multiple times

### ISSUE THREAD

**Issue by rvanoord** [bcc-code/bcc-vote#254]
During a recent live event, voter names were shown multiple times in the list of votes.

In this instance, some voters were shown once, whereas others were shown 2, 3 or 4 times. The issues affected multiple, but not all voters - but was visible on all user devices.

35 voters were online, and the issue occurred only for one question (of roughly 5)

User Story
In Drammen a member could vote twice:

https://projects.bcc.no/desk/tickets/6898616/messages

Acceptance Criteria

Each member should only be able to vote once

**Comment by ameliebawolski** [comment]
@rvanoord do you know if the users that where shown 2,3 or 4 times did try to vote several times?

**Comment by rvanoord** [comment]
No, I'm not sure about that.
