### ISSUE TITLE
Feedback page

### ISSUE THREAD

**Issue by ameliebawolski** [bcc-code/bcc-vote#265]
**User Story**
As a .... , I want to .... so that ....

**Additional Description**
at the end of a vote the user should be asked to give some feedback
Part of the last page

**Acceptance Criteria**
1. one textbox to answer  "did you experience any trouble?"  with submit button
2. optional rating 1-5 
3. users can skipp the feedback
4. follow design: https://www.figma.com/file/Eq4kNcMejzrIQWV6sD4e0C/BCC-Voting?node-id=1111%3A186

**Comment by lidalukashuk** [comment]
@ameliebawolski https://www.figma.com/file/Eq4kNcMejzrIQWV6sD4e0C/BCC-Voting?node-id=1111%3A186

**Comment by lidalukashuk** [comment]
@ameliebawolski 
Looks fine for me in general, but the space between is bigger than in the initial design (1) and shadows on the textbox below is probably wrong and it looks weird to me (2)
 
<img width="920" alt="Screenshot 2021-06-29 at 12 55 46" src="https://user-images.githubusercontent.com/33638539/123785938-6477ae80-d8d9-11eb-9cae-713c729c91e7.png">

**Comment by JakubC-projects** [comment]
I'll need to investigate it, thanks for information
