### ISSUE TITLE
Design change - buttons on home screen

### ISSUE THREAD

**Issue by ameliebawolski** [bcc-code/bcc-vote#269]
**User Story**
As a .... , I want to .... so that ....

**Additional Description**
....

**Acceptance Criteria**
1. Primary action for administrator on voting app is to administrate, therefore this should be the button highlited the most
2. Remove "church:", "role:"
2. Follow the design: https://www.figma.com/file/Eq4kNcMejzrIQWV6sD4e0C/BCC-Voting?node-id=79%3A1032

**Comment by lidalukashuk** [comment]
https://www.figma.com/file/Eq4kNcMejzrIQWV6sD4e0C/BCC-Voting?node-id=79%3A1032
