### ISSUE TITLE
Timeout error

### ISSUE THREAD

**Issue by JakubC-projects** [bcc-code/bcc-vote#273]
**User Story**
As a user I want to have smooth experience using the app

**Additional Description**
Some user experienced an error which should not occur
sentry event link: https://sentry.io/organizations/bcc-hj/issues/2479871948/events/d83da7e45196494abfa65ae01c366187

Support case: https://projects.bcc.no/desk/tickets/6898616/messages

**Acceptance Criteria**
1. Understand what happened and if possible fix the issue

root cause: ???

**Comment by StevenMalaihollo** [comment]
Looks resolved based on PR: https://github.com/bcc-code/bcc-membership/pull/508
