### ISSUE TITLE
High number of socket connection in the members app

### ISSUE THREAD

**Issue by JakubC-projects** [bcc-code/bcc-vote#274]
**Additional Description**
In the cloud console we can see in logs that the app generates sometimes even 10000 connections in the span of half an hour. 

**Acceptance Criteria**
1. Understand the issue and fix the problem

![image](https://user-images.githubusercontent.com/12196246/123938593-89325b80-d997-11eb-8826-bbbb980d270e.png)

https://console.cloud.google.com/logs/query;query=httpRequest.status%3D101;timeRange=2021-06-27T09:00:00.000Z%2F2021-06-28T01:40:00.000Z;cursorTimestamp=2021-06-28T01:39:09.281487Z?authuser=1&project=kinetic-center-276213&folder=true&organizationId=1075497630594&query=%0A

**Comment by philipdalen** [comment]
Potential fix - https://github.com/bcc-code/bcc-membership/pull/508
