### ISSUE TITLE
Bugsquashing - BCC Vote

### ISSUE THREAD

**Issue by rvanoord** [bcc-code/bcc-vote#313]
There are a number of minor bugs  / unhandled exceptions in BCC Vote (e.g. error when a session expired) which should be fixed. These errors come from Sentry.

- [x] #341
- [x] #340
- [x] #342
- [x] #346
- [x] #343
- [x] #344
- [ ] #345

**Comment by elpenny** [comment]
No. 4 - Poll is not active is probably already resolved.
