### ISSUE TITLE
What's this repo about?

### ISSUE THREAD

**Issue by kkuepper** [bcc-code/bcc-vote#437]
When looking at this repo I don't understand where I can find the voting app. Is there a url?

Also what kind of topics are being voted on? How does it differentiate from User Voice?

**Comment by StevenMalaihollo** [comment]
@kkuepper this is a product for (scheduled) voting for groups of people. Like the representatskaps meetings.

You should be able play around with it here: https://dev.vote.bcc.no/

**Comment by StevenMalaihollo** [comment]
Sorry for the late reply, only just saw this. 

If you have a more concrete improvement we can make you can create a new issue 👍🏽
