### ISSUE TITLE
Vote-admin couldn't create polling event for one specific role

### ISSUE THREAD

**Issue by amelienbawolski** [bcc-code/bcc-vote#443]
**User Story**
![image](https://user-images.githubusercontent.com/107836832/205031418-8a87975a-0f8f-429d-b91e-1b50648577f3.png)

https://projects.bcc.no/desk/tickets/10417165/messages

**Acceptance Criteria**
1. ADministrator should be able to create polling event

**Comment by zuzannamagdicz** [comment]
I got that error message when I didn't choose anything under Organization. Otherwise it worked to create an polling event

**Comment by amelienbawolski** [comment]
okay nice thanks for checking :) @zuzannamagdicz
