### ISSUE TITLE
same poll came up more the once

### ISSUE THREAD

**Issue by amelienbawolski** [bcc-code/bcc-vote#444]
**User Story**
https://projects.bcc.no/desk/tickets/10443804/messages

It seemed like the same poll came up more the once

other users described it as if it was jumping back and forth between results and poll.

**Acceptance Criteria**
1. As long as the administrator doesn't publish the same poll again it shouldn't show the same poll again

**Comment by zuzannamagdicz** [comment]
I couldn't reproduce it. 
If the admin doesn't open the polling event, it is not possible for the user to participate. 

Didn't experience any jumping back and forth between results and poll

**Comment by StevenMalaihollo** [comment]
Should reopen if it occurs more often / is reproducable
