### ISSUE TITLE
Add a timer on the event

### ISSUE THREAD

**Issue by amelienbawolski** [bcc-code/bcc-vote#453]
**User Story**
Det bør utvikles en funksjon som synliggjør for deltakere og møteansvarlige hvor mange som er innlogget på løsningen i appen (live), slik at ordstyrer har grunnlag for å si at majoriteten har votert.
**Additional Description**

**Acceptance Criteria**
1. add timer on top when a question is published
2. add participant count (of all possible participants)
3. Design:
https://www.figma.com/file/Eq4kNcMejzrIQWV6sD4e0C/01.00-BCC-Voting?type=design&node-id=2013-8319

4. correct design for timer: 
<img width="140" alt="image" src="https://github.com/bcc-code/bcc-vote/assets/107836832/6d5c9bfc-d013-4858-8358-5b669fa52bc3">

**Comment by StevenMalaihollo** [comment]
For just the timer and a basic count of participants (only participated): 3 hours

+ full count of participants (people that clicked on "Delta"): 6 Hours

**Comment by amelienbawolski** [comment]
timer estimate: 2 day

**Comment by KajaKozuchBCC** [comment]
Design: 
https://www.figma.com/file/Eq4kNcMejzrIQWV6sD4e0C/01.00-BCC-Voting?type=design&node-id=2013-8319
