### ISSUE TITLE
Update on voting group

### ISSUE THREAD

**Issue by amelienbawolski** [bcc-code/bcc-vote#454]
**User Story**
<img width="406" alt="image" src="https://user-images.githubusercontent.com/107836832/234802612-c14fdfe1-80fb-4eba-aec8-861fbb4a4936.png">

Det er behov for å utvikle mulighet for å velge hvem som skal kunne votere da årsmøter kun gjelder medlemmer, men andre møter kan gjelde f eks representanter eller delegater osv. 

Det er ønskelig at voting admin ser kun de roller i medlemsregisteret som kan knyttes til sin forening og hvor mange i foreningen som innehar den rollen.

Administrator bør også kunne velge mellom kategorier som deltakere, medlemmer, tilhørige og alle kategorier. 
Denne funksjonen må være en flervalgsfunksjon (f eks kun tilhørige og medlemmer skal kunne votere).

**Acceptance Criteria**
1. Limit list of roles to only the once that are available to a local church (central admin, developer, support, sentral informasjonsarbeider, informasjonsarbeider, arrangementansvarlig, central church leader, shouldn't be in the list)
2. Add extra categories for membership types: "members" , "affiliate", "participants"
3. Admin can select all categories
4. If e.g. only **members** is chosen than only members of that organisation can vote
5. Design: https://www.figma.com/file/Eq4kNcMejzrIQWV6sD4e0C/01.00-BCC-Voting?type=design&node-id=2027-9513

**Comment by JakubC-projects** [comment]
@amelienbawolski I'm not sure I understand, do we want to disallow persons from Netherslands from voting or creating voting events?

**Comment by StevenMalaihollo** [comment]
Estimated at 8 hours

**Comment by amelienbawolski** [comment]
new estimate: 10 hours

**Comment by KajaKozuchBCC** [comment]
Design: https://www.figma.com/file/Eq4kNcMejzrIQWV6sD4e0C/01.00-BCC-Voting?type=design&node-id=2027-9513
