### ISSUE TITLE
Status changes on poll

### ISSUE THREAD

**Issue by amelienbawolski** [bcc-code/bcc-vote#461]
**User Story**
Ikke aktive poller bør ikke være synlige for sluttbruker. 

En poll bør endres fra aktiv til finished automatisk etter siste spørsmål. Dette må kunne overstyres manuelt hvis det er behov for å aktivere den igjen.

**Acceptance Criteria**
1. only acitve polls should be visible to end users
2. the polls status should be set to finished after all questions were published and closed

**Comment by amelienbawolski** [comment]
Estimate: 1 day

**Comment by StevenMalaihollo** [comment]
![image](https://github.com/bcc-code/bcc-vote/assets/39584351/bd760460-f8ab-4760-a1e9-06cf36f9a672)
End result
