### ISSUE TITLE
Questions should be still visible after voting event is set to finished

### ISSUE THREAD

**Issue by amelienbawolski** [bcc-code/bcc-vote#462]
**User Story**
<img width="467" alt="image" src="https://user-images.githubusercontent.com/107836832/234809671-a6d98bc3-a6bb-4ea5-9e8d-cec357cf4b78.png">

Endring av status ikke aktiv og aktiv bør kunne overstyres manuelt slik at man kan tilbakestille en synlig poll til å ikke vises for sluttbruker.

**Acceptance Criteria**
1. Questions should be still visible after the event is set to finished

**Comment by amelienbawolski** [comment]
estimate: 6 hours

**Comment by StevenMalaihollo** [comment]
@amelienbawolski me and Jake are a bit uncertain about this task;

1. The image in the issue shows that the Polling event is set to finished. But don't you mean that when a Poll (question) is republishable it can still be edited?
![Image](https://github.com/bcc-code/bcc-vote/assets/39584351/d4fd5ce0-2a8e-4ba0-9f4c-890e015f4e44)

2. When editing anything about a Poll (question) should all the existing votes be reset? For me it would be weird if an admin could go back and edit the answer text someone gave.  

We can also take a call to clear this up.

**Comment by amelienbawolski** [comment]
@StevenMalaihollo yes I think it would be helpful to discuss this
