### ISSUE TITLE
You are voting as... question before participation update

### ISSUE THREAD

**Issue by amelienbawolski** [bcc-code/bcc-vote#463]
**User Story**
<img width="343" alt="image" src="https://user-images.githubusercontent.com/107836832/234810812-9fae8fb9-7d2c-472d-be5b-0282b1fd0efa.png">

Det er ønskelig at bekreftelsen man får opp for å bekrefte person når man logger inn utvides med følgende tekst: 

**Acceptance Criteria**
1.Update text to: 

Jeg, [navn], bekrefter at jeg ønsker å delta i [name of voting event], og samtykker til at data om meg vil bli behandlet i forbindelse med dette. 

Ikke deg? Vennligst logg inn på nytt 

(Logg ut)		 	(Godkjenn )

2. use same design as before just with updated text

**Comment by amelienbawolski** [comment]
Estimate: 1 hour

**Comment by KajaKozuchBCC** [comment]
Design:
https://www.figma.com/file/Eq4kNcMejzrIQWV6sD4e0C/01.00-BCC-Voting?type=design&node-id=2024-13385
