### ISSUE TITLE
Restarting polling event will reset all answers and participation

### ISSUE THREAD

**Issue by amelienbawolski** [bcc-code/bcc-vote#468]
**Additional Description**
Restarting polling event will lead to reseting the whole event - question: are you sure that you want to restart this polling event? By pressing "start polling event" the previous results of all questions will be deleted. 

![Image](https://github.com/bcc-code/bcc-vote/assets/107836832/720e86d6-b06c-46f8-a309-1e878c871214)

**Acceptance Criteria**
1. Only for finished event 
2. when clicking on "start polling event" for a "finished event" this event will reset the event, this means all answers deleted and all participants are also deleted
3. by clicking on the "start polling event" will the admin need to confirm the "are you sure pop up:
you sure that you want to restart this polling event? By pressing "start polling event" the previous results of all questions will be deleted. 
4. Reset everything - button to restart

https://www.figma.com/file/Eq4kNcMejzrIQWV6sD4e0C/01.00-BCC-Voting?type=design&node-id=2013-8319&t=V0vC5uISPCJDrzC9-0

**Comment by amelienbawolski** [comment]
estimate: 1 d

**Comment by JakubC-projects** [comment]
It's been decided that we're going to have a separte button for resetting the polling event. Desing: https://www.figma.com/file/Eq4kNcMejzrIQWV6sD4e0C/01.00-BCC-Voting?type=design&node-id=2133-10452&t=g5QEPRaucsY0cmU6-4
