### ISSUE TITLE
Delete all polling events after 12 months

### ISSUE THREAD

**Issue by amelienbawolski** [bcc-code/bcc-vote#469]
**Acceptance Criteria**
1. after 12 months will the polling event (including report) automatically deleted

**Comment by amelienbawolski** [comment]
estimate: 1 d

**Comment by amelienbawolski** [comment]
@JakubC-projects not sure if this needs more description?

**Comment by zuzannamagdicz** [comment]
By "deleted" you mean "archived? @amelienbawolski  Or should they be completely deleted?  I can still see the old events under archived


![Image](https://github.com/bcc-code/bcc-vote/assets/82595752/a5d25883-4f71-4037-a2e3-1a866e5b24be)
