### ISSUE TITLE
Live Results page is not updating

### ISSUE THREAD

**Issue by StevenMalaihollo** [bcc-code/bcc-vote#490]
**Additional Description**
![image](https://github.com/bcc-code/bcc-vote/assets/39584351/91b139ed-e115-4821-943a-d456f522bf85)

**Acceptance Criteria**
1. The Live events page should always be up to date with the latest Poll
2. The Live events page should always be up to date with the latest Poll results
3. Also when there is existing initial state before opening the page.

root cause: b50766f56f2fa3b28ac395cadaafd0f2e6082143

**Comment by u12206050** [comment]
What do you guys use for real time events?

**Comment by JakubC-projects** [comment]
@u12206050 We use firestore for it

**Comment by JakubC-projects** [comment]
@StevenMalaihollo Are you working on this, it looks like you've put it on Development but haven't assigned anyone

**Comment by StevenMalaihollo** [comment]
@JakubC-projects I am now!
