### ISSUE TITLE
Participant - confirm answer 

### ISSUE THREAD

**Issue by ameliebawolski** [bcc-code/bcc-vote#95]
**User Story**
As a member , I want to confirm my answer so that I don't accidentily click on the wrong answer 

**Additional Description**
Confirmation and answer should be seperated. e.g. click on "yes" -> "vote" you get up in a second step "you are voting with yes and therefore agreeing to quesiton 1" 

**Acceptance Criteria**
1.  step1 clicking on answer options and then on vote 
2. step 2 you get up confirmation text. User has to either confirm or can cancel and take an other choice

**Comment by lidalukashuk** [comment]
https://www.figma.com/file/Eq4kNcMejzrIQWV6sD4e0C/BCC-Voting?node-id=464%3A234
