### ISSUE TITLE
Administrator -  Answers - confirmation and availbility

### ISSUE THREAD

**Issue by ameliebawolski** [bcc-code/bcc-vote#99]
**User Story**
As an administrator, I want to choose when a user should confirm their answer so that I don't accidentily click on the wrong answer

**Additional Description**
info text: By activating the "answer confirmation" you can decide if voters will be asked to confirm their decision. You have the possibility to edit the confirmation below". 

**Acceptance Criteria**
1. Checkbox want confirmation for answer options
2. only than will answer confirmation be shown
3. Confirmation text will already be in the text box but can be edit for yes: yes I agree with: [Question]
4. Rename "Answer Explanation" to "confirmation (Option 1)",  "confirmation (Option 2)"

5. Titel for Availability for name and vote --> Results visibility
6. Description or info: Name and vote will be avaible for:
7. than options: public (everybody) ; event creator (Hidden for members); anaymous (hidden for everybody)

**Comment by lidalukashuk** [comment]
@ameliebawolski  https://www.figma.com/file/Eq4kNcMejzrIQWV6sD4e0C/BCC-Voting?node-id=311%3A4844
